# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy


In [ ]:
pip install numpy

install pip

## Using NumPy

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. 
Important aspects of Numpy: vectors,arrays,matrices, and number generation. 
# Numpy Arrays

 Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
type(my_list)


list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,2)

array([0, 1])

In [8]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.arange(30 , 0 , -3)

array([30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

In [11]:
np.arange(0 , 40 ,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

### zeros and ones

Generate arrays of zeros or ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5,9))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:

np.linspace(0,10,endpoint= False)

In [ ]:
np.linspace(0,10,3)

## eye

Creates an identity matrix

In [17]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [18]:
np.random.rand(2)

array([0.84225869, 0.03795854])

In [19]:
np.random.rand(2,2)

array([[0.10051383, 0.36315208],
       [0.81269932, 0.61889544]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(2)

array([ 0.2864191 , -0.29991898])

In [21]:
np.random.randn(5,5)

array([[-5.45413668e-01, -5.34761918e-02, -1.03976762e+00,
         3.71246634e-01, -8.53166003e-01],
       [ 1.29999647e-01, -1.50639910e-03,  1.38757129e+00,
         7.82693315e-01, -1.50326712e+00],
       [ 5.82589123e-01,  4.84771042e-01,  1.21079754e+00,
        -9.52495004e-01, -9.84353190e-01],
       [-1.37073615e+00, -3.49172541e-01,  2.26220699e+00,
        -3.06499765e-01, -2.14441941e-01],
       [-4.90273059e-01,  6.76422739e-01,  2.09022001e-02,
        -6.82367050e-03, -1.07003179e+00]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100)

71

In [23]:
np.random.randint(1,100,10)

array([59, 19, 51, 17, 23, 47, 19,  9, 34, 23])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

In [ ]:
print(arr.shape)

In [ ]:
ranarr

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
print(arr1.shape)
print(arr1)

In [ ]:
arr1 =arr.reshape(5,5)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)


In [ ]:
arr.reshape(25,1).shape

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

# Great Job!

In [25]:
import pandas as pd

In [26]:
df = pd.DataFrame({"Name": ["Braund, Mr. Owen Harris","Allen, Mr. William Henry","Bonnell, Miss. Elizabeth",],
         "Age": [22, 35, 58],
          "Sex": ["male", "male", "female"],
      }
   )

In [27]:
df

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [29]:
df["Name"]

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2    Bonnell, Miss. Elizabeth
Name: Name, dtype: object

In [33]:
df["Age"].min()

22

In [ ]:


matplotlib
pandas
numpy