In [3]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [9]:
my_arrray=np.array(my_list)
print(type(my_arrray))
print(my_arrray)
np.array(my_list)

<class 'numpy.ndarray'>
[1 2 3]


array([1, 2, 3])

In [41]:
my_matrix=[["s","4",3],[4,5,6],[7,8,9]]
print(my_matrix)

[['s', '4', 3], [4, 5, 6], [7, 8, 9]]


In [42]:
t=np.array(my_matrix)
t

array([['s', '4', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

In [43]:
t.dtype

dtype('<U1')

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
s=list(np.arange(30,-1,-3))

In [20]:
p=list(np.arange(0,41,4))

In [21]:
c=[s,p]
np.array(c)

array([[30, 27, 24, 21, 18, 15, 12,  9,  6,  3,  0],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40]])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.linspace(0,50,100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [31]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(4)

array([0.28654036, 0.30913333, 0.91792171, 0.95091142])

In [35]:
np.random.rand(4,4)

array([[0.58849823, 0.68338153, 0.24635935, 0.98749105],
       [0.55533591, 0.06746699, 0.12048024, 0.90090042],
       [0.00099541, 0.92100063, 0.1468384 , 0.24471826],
       [0.82895004, 0.69668268, 0.91009154, 0.35764238]])

In [36]:
np.random.rand(4,4,2)

array([[[0.21458989, 0.12793727],
        [0.83158222, 0.58380335],
        [0.50421454, 0.47402595],
        [0.3444869 , 0.24833017]],

       [[0.22073569, 0.46824326],
        [0.44542339, 0.07094586],
        [0.44938517, 0.5975539 ],
        [0.14154608, 0.85275812]],

       [[0.26080083, 0.54473771],
        [0.37747686, 0.98085316],
        [0.75914772, 0.48200721],
        [0.90404456, 0.58670719]],

       [[0.46543561, 0.42126654],
        [0.99072486, 0.45538064],
        [0.68358549, 0.92300144],
        [0.83255245, 0.29278085]]])

In [23]:
arr=np.arange(1,26)
print(arr.shape)
print(arr)
print(arr.reshape(5,5))

(25,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [83]:
rarr=np.random.randint(0,50,16)
rarr

array([46, 30, 46, 13,  9, 19, 24, 34, 15, 43, 38, 37, 39, 31,  2,  7])

In [26]:
print(rarr.max())
print(rarr.argmax())
print(rarr.min())
print(rarr.argmin())

44
12
2
9


In [27]:
arr.dtype

dtype('int64')

In [76]:
arr=np.arange(11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr[8]

8

In [70]:
arr[-1:-5:-1]

array([10,  9,  8,  7])

In [77]:
print(arr)
sliceofarr=arr[0:5]
sliceofarr[:]=100
print(sliceofarr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [78]:
ar=arr[0:5]
print(ar)
ar1=ar.copy()
ar[1:3]=99
print(ar)
print(ar1)

[100 100 100 100 100]
[100  99  99 100 100]
[100 100 100 100 100]


In [86]:
arr_2D=np.array(([1,2,3],[2,3,4],[5,6,7],[3,8,4]))
arr_2D

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7],
       [3, 8, 4]])

In [87]:
arr_2D[2]

array([5, 6, 7])

In [88]:
arr_2D[:2]

array([[1, 2, 3],
       [2, 3, 4]])

In [91]:
arr_2D[:2,:2]

array([[1, 2],
       [2, 3]])

In [92]:
arr_2D[2,:2]

array([5, 6])

In [99]:
arr_2D[[1,2,3]]

array([[2, 3, 4],
       [5, 6, 7],
       [3, 8, 4]])